rootProject.name = "AstraStore"

include(
        "api-gateway",
        "auth",
        "upload",
        "download",
        "metadata",
        "placement",
        "replication",
        "monitoring",
        "storage-node",
        "astrastore-shared"
)

project(":api-gateway").name    = "api-gateway"
project(":auth").name           = "auth"
project(":upload").name         = "upload"
project(":download").name       = "download"
project(":metadata").name       = "metadata"
project(":placement").name      = "placement"
project(":replication").name    = "replication"
project(":monitoring").name     = "monitoring"
project(":storage-node").name    = "storage-node"
project(":astrastore-shared").name = "astrastore-shared"