spring:
  application:
    name: auth-service
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.astrastore: DEBUG
    org.springframework.security: INFO
